server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: test
    group:
      test: test,mail
      dev: dev, mail, dev-db
      real: real, mail, real-db
      set1: set1, mail, real-db
      set2: set2, mail, real-db