spring:
  config:
    activate:
      on-profile: production
  session:
    store-type: jdbc
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  messages:
    basename: messages,errors

file:
  directory: /Users/aaron/uploadFiles/