server:
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: prod
    group:
      test: test,mail
      dev: dev, mail, dev-db
      prod: real-port, real, mail, real-db, management
      set1: set1-port, real, mail, real-db, management
      set2: set2-port, real, mail, real-db, management