server:
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: test
    group:
      test: test,mail
      dev: dev, mail, dev-db
      real: real-port, real, mail, real-db
      set1: real-port, real, mail, real-db
      set2: set2-port, real, mail, real-db