server:
  port: 8080
  servlet:
    session:
      timeout: 43200 # 12h
  tomcat:
    mbeanregistry:
      enabled: true

spring:

  config:
    activate:
      on-profile: test

  session:
    store-type: redis
    redis:
      repository-type: indexed

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

  thymeleaf:
    cache: 'false'

  datasource:
    url: jdbc:h2:mem:reon;MODE=MARIADB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: asfdsafdasffsadf
            client-secret: asdfsafasdfdasdfas
            scope: email, profile

logging:
  level:
    org:
      hibernate:
        nodeValue: info # basic log level for all messages
        stat: debug # Statistics and slow queries
        SQL_SLOW: info # Statistics and slow queries
        SQL: debug # SQL statements and parameters
        cache: debug # 2nd Level Cache
        orm:
          jdbc:
            bind: trace # SQL statements and parameters

app:
  reon:
    client-name: reon
    client-id: 235df110-bd70-11ee-aa8b-e30685fde2fa

file:
  upload:
    location: /Users/aaron/reon/uploadFiles/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management/actuator
