server:
  port: 8080

spring:

  config:
    activate:
      on-profile: dev

  session:
    store-type: redis
    redis:
      repository-type: indexed

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
    session:
      timeout: 3600

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  messages:
    basename: messages,errors

file:
  directory: /Users/aaron/reon/uploadFiles/