server:
  port: 8080

spring:

  config:
    activate:
      on-profile: test

  session:
    store-type: redis
    redis:
      repository-type: indexed

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
    session:
      timeout: 3600

  thymeleaf:
    cache: 'false'

  datasource:
    url: jdbc:h2:mem:reon;MODE=MARIADB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  messages:
    basename: messages,errors

logging:
  level:
    root: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE
        SQL: DEBUG

file:
  upload:
    location: /Users/aaron/reon/uploadFiles/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management/actuator
