server:
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: prod
    group:
      test: test, mail, dev-oauth
      dev: dev, mail, dev-db, dev-oauth
      prod: real-port, real, mail, real-db, management, real-oauth
      set1: set1-port, real, mail, real-db, management, real-oauth
      set2: set2-port, real, mail, real-db, management, real-oauth